/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chortitzer.industria.zebra;

import com.chortitzer.industria.zebra.domain.fps.TblFpsLotes;
import com.chortitzer.industria.zebra.domain.fps.TblFpsTambores;
import com.chortitzer.industria.zebra.util.Utils;
import java.beans.Beans;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Industria
 */
public class PanelFps extends javax.swing.JPanel {

    /**
     * Creates new form PanelFps
     */
    public PanelFps() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }

        tblLotes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        ListSelectionModel selectionModel = tblLotes.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                tblFpsTamboresQuery = entityManager.createQuery("SELECT t FROM TblFpsTambores t WHERE t.idLote = :idLote");
                tblFpsTamboresQuery.setParameter("idLote", tblFpsLotesList.get(tblLotes.getSelectedRow()));
                tblFpsTamboresList.clear();
                tblFpsTamboresList.addAll(tblFpsTamboresQuery.getResultList());               
                btnPrint.setEnabled(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        cboNombreComun = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("fps_PU").createEntityManager();
        tblFpsLotesQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM TblFpsLotes t ORDER BY t.fecha DESC");
        tblFpsLotesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(tblFpsLotesQuery.getResultList());
        tblFpsTamboresQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM TblFpsTambores t");
        tblFpsTamboresList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(tblFpsTamboresQuery.getResultList());
        netoTableCellRenderer1 = new com.chortitzer.industria.zebra.util.NetoTableCellRenderer();
        btnCancel = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTambores = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        cboNombreComun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargando..." }));
        cboNombreComun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNombreComunActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre Comun");

        netoTableCellRenderer1.setText("netoTableCellRenderer1");

        btnCancel.setText("CANCELAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(204, 255, 204));
        btnPrint.setText("IMPRIMIR");
        btnPrint.setEnabled(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jLabel9.setText("Tambores");

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFpsLotesList, tblLotes);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idFabrica}"));
        columnBinding.setColumnName("Nro. Lote");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fecha}"));
        columnBinding.setColumnName("Fecha");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tblLotes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblLotesPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblLotes);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFpsTamboresList, tblTambores);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idFabrica}"));
        columnBinding.setColumnName("Id Fabrica");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pesoBruto}"));
        columnBinding.setColumnName("Peso Bruto");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pesoTara}"));
        columnBinding.setColumnName("Peso Tara");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pesoTara}"));
        columnBinding.setColumnName("Peso Neto");
        columnBinding.setColumnClass(Double.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tblTambores);
        if (tblTambores.getColumnModel().getColumnCount() > 0) {
            tblTambores.getColumnModel().getColumn(3).setCellRenderer(netoTableCellRenderer1);
        }

        jLabel10.setText("Lote");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(441, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(451, Short.MAX_VALUE)))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        Utils.rawPrint(getZpl());
        //System.out.println(getZpl());
    }//GEN-LAST:event_btnPrintActionPerformed

    private void cboNombreComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNombreComunActionPerformed
        try {

        } catch (Exception e) {
            Utils.messageBox(e.getStackTrace().toString());
        }
    }//GEN-LAST:event_cboNombreComunActionPerformed

    private void tblLotesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblLotesPropertyChange


    }//GEN-LAST:event_tblLotesPropertyChange

    private String getZpl() {
            String result = "";            
            TblFpsLotes lote = tblFpsLotesList.get(tblLotes.getSelectedRow());
            TblFpsTambores tambor;
            String dLote = String.valueOf(lote.getIdFabrica());            
            SimpleDateFormat dateF = new SimpleDateFormat("dd/MM/yyyy");
            String dFecha = dateF.format(lote.getFecha());
            String dObs = lote.getObs();
            if(dObs==null){                
                dObs = "";
            }

            int nRow = tblFpsTamboresList.size();
            for (int i = 0 ; i < nRow ; i++){    
            //int i = 0;
                tambor = tblFpsTamboresList.get(i);
                    String dIdFabrica = String.valueOf(tambor.getIdFabrica());
                    String dBruto = getAlignedNumber(tambor.getPesoBruto());
                    String dTara = getAlignedNumber(tambor.getPesoTara());
                    String dNeto = getAlignedNumber(tambor.getPesoBruto()-tambor.getPesoTara());
                    
                    result += "^XA" +                            
                            "^PW799" +
                            "^FT64,1010^XGE:LC100.GRF,1,1^FS" +
                            "^FT94,845^A0B,51,50^FH\\^FDAceite Esencia de Palo Santo^FS" +
                            "^FT158,845^A0B,51,50^FH\\^FDGuaiacwood Oil^FS" +                            
                            "^FT285,1100^AAB,44,24^FH\\^FDFecha / Date: "+dFecha+"^FS" +
                            "^FT330,1100^AAB,44,24^FH\\^FDLote / Batch: "+dLote+"^FS" +
                            "^FT375,1100^AAB,44,24^FH\\^FDEnvase Nro. / Container Nr.: "+dLote+"-"+dIdFabrica+"^FS" +
                            "^FT420,1100^AAB,44,24^FH\\^FDPeso Bruto / Gross weight: "+dBruto+" Kg^FS" +
                            "^FT465,1100^AAB,44,24^FH\\^FDPeso Tara / Tare weight:   "+dTara+" Kg^FS" +
                            "^FT510,1100^AAB,44,24^FH\\^FDPeso Neto / Net weight:    "+dNeto+" Kg^FS" +
                            "^FT645,1100^AAB,44,24^FB1020,2,0,L^FH\\^FD"+dObs+"^FS" +
                            //"^FT600,1100^AAB,44,24^FH\\^FDROBERTET INC. - PO# 103759^FS" +
                            "^FT685,885^A0B,28,28^FB821,1,0,R^FH\\^FDHandling instructions: Dry Charge – Room Temperature^FS" +
                            "^FT719,885^A0B,28,28^FB821,1,0,R^FH\\^FDProducido por / Manufactured by: COOPERATIVA CHORTITZER LTDA.^FS" +
                            "^FT753,885^A0B,28,28^FB821,1,0,R^FH\\^FDPais de origen / Country of origin: PARAGUAY^FS" +
                            "^PQ1,0,1,Y^XZ";                
            }
            return result;
    }
    
    private String getAlignedNumber(double num){
        DecimalFormat df = new DecimalFormat("##0.0");
        String res = df.format(num);        
        return "                   ".substring(0, 5-res.length())+res;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox cboNombreComun;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.chortitzer.industria.zebra.util.NetoTableCellRenderer netoTableCellRenderer1;
    private java.util.List<com.chortitzer.industria.zebra.domain.fps.TblFpsLotes> tblFpsLotesList;
    private javax.persistence.Query tblFpsLotesQuery;
    private java.util.List<com.chortitzer.industria.zebra.domain.fps.TblFpsTambores> tblFpsTamboresList;
    private javax.persistence.Query tblFpsTamboresQuery;
    private javax.swing.JTable tblLotes;
    private javax.swing.JTable tblTambores;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
