/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chortitzer.industria.zebra;

import com.chortitzer.industria.zebra.util.Utils;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;

/**
 *
 * @author Industria
 */
public class PanelAlgodon extends javax.swing.JPanel {

    public PanelAlgodon() {
        initComponents();
        txtZafra.setText(String.valueOf(LocalDateTime.now().getYear()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtDesde = new org.jdesktop.swingx.JXTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnPrintSmall = new javax.swing.JButton();
        txtZafra = new org.jdesktop.swingx.JXTextField();
        txtHasta = new org.jdesktop.swingx.JXTextField();

        btnCancel.setText("CANCELAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel10.setText("Zafra:");

        txtDesde.setText("1");

        jLabel11.setText("Hasta Fardo Nº:");

        jLabel12.setText("Desde Fardo Nº:");

        btnPrintSmall.setBackground(new java.awt.Color(204, 255, 204));
        btnPrintSmall.setText("IMPRIMIR PRQUEÑO");
        btnPrintSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintSmallActionPerformed(evt);
            }
        });

        txtHasta.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel)
                    .addComponent(btnPrintSmall)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtZafra, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtZafra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPrintSmall, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPrintSmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintSmallActionPerformed
        Utils.rawPrint(getZplSmall());
        System.out.println(getZplSmall());
    }//GEN-LAST:event_btnPrintSmallActionPerformed

    private String getZplSmall() {
        String hastaNr = String.format("%05d", Integer.valueOf(txtHasta.getText()));
        return "^XA"
                + "^MTD"
                + "^PW799"
                //"^FT64,256^XGE:CCLOGO20.GRF,1,1^FS" +
                //"^FO27,25^GB746,1100,1^FS" +
                + "^FT590,60^A0N,30,31^FB220,1,0,L^FH\\^FDZafra: " + txtZafra.getText() + "^FS"
                + "^FT590,120^A0N,30,31^FB220,1,0,L^FH\\^FDFardo: " + hastaNr + "^SFAAAAAAAddddd,-1" + "^FS"
                + "^FT305,60^A0N,30,31^FB220,1,0,L^FH\\^FDZafra: " + txtZafra.getText() + "^FS"
                + "^FT305,120^A0N,30,31^FB220,1,0,L^FH\\^FDFardo: " + hastaNr + "^SFAAAAAAAddddd,-1" + "^FS"
                + "^FT15,60^A0N,30,31^FB220,1,0,L^FDZafra: " + txtZafra.getText() + "^FS"
                + "^FT15,120^A0N,30,31^FB220,1,0,L^FH\\^FDFardo: " + hastaNr + "^SFAAAAAAAddddd,-1" + "^FS"
                + "^PQ" + String.valueOf(Integer.valueOf(txtHasta.getText()) - Integer.valueOf(txtDesde.getText()) + 1) + ",1,0,Y^XZ";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrintSmall;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private org.jdesktop.swingx.JXTextField txtDesde;
    private org.jdesktop.swingx.JXTextField txtHasta;
    private org.jdesktop.swingx.JXTextField txtZafra;
    // End of variables declaration//GEN-END:variables
}
