/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chortitzer.industria.zebra;

import com.chortitzer.industria.zebra.util.Utils;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author Industria
 */
public class PanelDet extends javax.swing.JPanel {

    /**
     * Creates new form PanelFps
     */
    public PanelDet() {
        initComponents();
        Calendar calendar = Calendar.getInstance();
        dtpFecha.setDate(calendar.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dtpFecha = new org.jdesktop.swingx.JXDatePicker();
        txtCantidad = new org.jdesktop.swingx.JXTextField();

        btnCancel.setText("CANCELAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(204, 255, 204));
        btnPrint.setText("IMPRIMIR");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jLabel9.setText("Cantidad:");

        jLabel10.setText("Fecha:");

        txtCantidad.setText("10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dtpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(364, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        Utils.rawPrint(getZpl());
        //System.out.println(getZpl());
    }//GEN-LAST:event_btnPrintActionPerformed

    private String getZpl() {
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        return "^XA"
                + "^PW799"
                + "^FT64,256^XGE:CCLOGO20.GRF,1,1^FS"
                + "^FO27,25^GB746,1100,1^FS"
                + "^FT321,157^A0N,68,69^FB379,1,0,C^FH\\^FDDETERGENTE^FS"
                + "^FT321,242^A0N,68,69^FB379,1,0,C^FH\\^FDINDUSTRIAL^FS"
                + "^FO83,325^GB631,177,1^FS"
                + "^FT105,380^A0N,37,38^FH\\^FDComposicion: Agua, Dodecilsulfonato ^FS"
                + "^FT105,426^A0N,37,38^FH\\^FDde Sodio, Cocamida DEA, Urea, ^FS"
                + "^FT105,472^A0N,37,38^FH\\^FDCloruro de Sodio, Formaldehido^FS"
                + "^FT87,747^A0N,135,139^FH\\^FD" + df.format(dtpFecha.getDate()) + "^FS"
                + "^FT87,591^A0N,28,28^FH\\^FDFecha de Elaboraciosn:^FS"
                + "^FT182,877^A0N,39,38^FB435,1,0,C^FH\\^FDProducido para uso propio ^FS"
                + "^FT182,925^A0N,39,38^FB435,1,0,C^FH\\^FDen instalaciones de la ^FS"
                + "^FT182,973^A0N,39,38^FB435,1,0,C^FH\\^FDCooperativa Chortitzer Ltda.^FS"
                + "^FT214,1034^A0N,23,24^FB372,1,0,C^FH\\^FDElaborado por el Complejo Industrial.^FS"
                + "^FT214,1062^A0N,23,24^FB372,1,0,C^FH\\^FDTel. (0492) 418 345^FS"
                + "^FT214,1090^A0N,23,24^FB372,1,0,C^FH\\^FDeMail: labdinsutria@chortitzer.com.py^FS"
                + "^PQ" + txtCantidad.getText() + ",1,0,Y^XZ";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private org.jdesktop.swingx.JXDatePicker dtpFecha;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private org.jdesktop.swingx.JXTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
