/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chortitzer.industria.zebra;

import com.chortitzer.industria.zebra.util.Utils;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author Industria
 */
public class PanelMungRecepcion extends javax.swing.JPanel {

    public PanelMungRecepcion() {
        initComponents();
        Calendar calendar = Calendar.getInstance();
        dtpFecha.setDate(calendar.getTime());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dtpFecha = new org.jdesktop.swingx.JXDatePicker();
        txtLote = new org.jdesktop.swingx.JXTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCantidad = new org.jdesktop.swingx.JXTextField();

        btnCancel.setText("CANCELAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(204, 255, 204));
        btnPrint.setText("IMPRIMIR");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jLabel9.setText("Cantidad:");

        jLabel10.setText("Fecha:");

        jLabel12.setText("Nombre Productor:");

        txtCantidad.setText("10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel)
                    .addComponent(btnPrint)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        Utils.rawPrint(getZpl());
        System.out.println(getZpl());
    }//GEN-LAST:event_btnPrintActionPerformed

    private String getZplSmall() {
        return "^XA"
                + "^PW799"
                + //"^FT64,256^XGE:CCLOGO20.GRF,1,1^FS" +
                //"^FO27,25^GB746,1100,1^FS" +
                "^FT590,60^A0N,30,31^FB220,1,0,L^FH\\^FDLote: " + String.format("%04d", Integer.valueOf(txtLote.getText())) + "^FS"
                + "^FT590,120^A0N,30,31^FB220,1,0,L^FH\\^FDBolsa: " + "001^SFAAAAAAAddd,3" + "^FS"
                + "^FT305,60^A0N,30,31^FB220,1,0,L^FH\\^FDLote: " + String.format("%04d", Integer.valueOf(txtLote.getText())) + "^FS"
                + "^FT305,120^A0N,30,31^FB220,1,0,L^FH\\^FDBolsa: " + "002^SFAAAAAAAddd,3" + "^FS"
                + "^FT15,60^A0N,30,31^FB220,1,0,L^FDLote: " + String.format("%04d", Integer.valueOf(txtLote.getText())) + "^FS"
                + "^FT15,120^A0N,30,31^FB220,1,0,L^FH\\^FDBolsa: " + "003^SFAAAAAAAddd,3" + "^FS"
                + "^PQ" + String.valueOf(Math.round(Integer.valueOf(txtCantidad.getText()) / 3)) + ",1,0,Y^XZ";
    }

    private String getZpl() {
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        String response = "^XA"
                + "^PW799"
                + "^FT64,256^XGE:CCLOGO20.GRF,1,1^FS"
                + "^FO27,25^GB746,1100,1^FS"
                + "^FT321,157^A0N,68,69^FB379,1,0,C^FH\\^FDPOROTO^FS"
                + "^FT321,242^A0N,68,69^FB379,1,0,C^FH\\^FDMUNG^FS"
                + "^FT87,380^A0N,28,28^FH\\^FDProductor:^FS"
                + "^FT87,520^A0N,75,79^FH\\^FD" + txtLote.getText() + "^FS"
                + "^FT87,590^A0N,28,28^FH\\^FDFecha de Recepcion:^FS"
                + "^FT87,730^A0N,135,139^FH\\^FD" + df.format(dtpFecha.getDate()) + "^FS"
                + "^FT87,980^A0N,58,59^FH\\^FDBolsa Nro.: 001^SFAAAAAAAAAAAAAddd,1^FS";
        response += "^FT5,1034^A0N,23,24^FB799,1,0,C^FH\\^FDElaborado por Cooperativa Chortitzer Ltda.^FS"
                + "^FT5,1062^A0N,23,24^FB799,1,0,C^FH\\^FDTel. (0492) 418 244^FS"
                + "^FT5,1090^A0N,23,24^FB799,1,0,C^FH\\^FDAvda. Central - Loma Plata - -Dpto. Boqueron - PY^FS"
                + "^PQ" + txtCantidad.getText() + ",1,0,Y^XZ";

        return response;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private org.jdesktop.swingx.JXDatePicker dtpFecha;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private org.jdesktop.swingx.JXTextField txtCantidad;
    private org.jdesktop.swingx.JXTextField txtLote;
    // End of variables declaration//GEN-END:variables
}
