/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chortitzer.industria.zebra;

import ca.odell.glazedlists.GlazedLists;
import ca.odell.glazedlists.swing.AutoCompleteSupport;
import com.chortitzer.industria.zebra.domain.lab.LabSemillasEspecies;
import com.chortitzer.industria.zebra.util.Utils;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Industria
 */
public class PanelSemillas extends javax.swing.JPanel {

    LabSemillasEspecies semillaActual;

    String nombreComun;
    String nombreCientifico;
    String variedad;
    String categoria;
    String lote;
    String zaranda;
    String pureza;
    String germinacion;
    String cosecha;
    String peso;
    String tratamiento;

    /**
     * Creates new form PanelSya
     */
    public PanelSemillas() {
        initComponents();
        Date hoy = new Date();
        Calendar c = Calendar.getInstance();
        c.setTime(hoy);

        List<LabSemillasEspecies> semillasEntityList = em.createQuery("select t from LabSemillasEspecies t order by t.nombreComun").getResultList();
        //AutoCompleteDecorator.decorate(this.cboEmpresa);

        AutoCompleteSupport support = AutoCompleteSupport.install(
                this.cboNombreComun, GlazedLists.eventListOf(semillasEntityList.toArray()));

        cboNombreComun.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        em = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("lab_PU").createEntityManager();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtVariedad = new javax.swing.JTextField();
        cboNombreComun = new javax.swing.JComboBox();
        txtNombreCientifico = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        cboCategoria = new javax.swing.JComboBox();
        txtPureza = new javax.swing.JTextField();
        txtZaranda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtGerminacion = new javax.swing.JTextField();
        txtTratamiento = new javax.swing.JTextField();
        txtCosecha = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        rbVC = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jLabel11.setText("Variedad");

        jLabel13.setText("Cosecha");

        jLabel6.setText("VC/GM");

        jLabel7.setText("Nombre Comun");

        jLabel5.setText("Zaranda");

        txtVariedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVariedadActionPerformed(evt);
            }
        });

        cboNombreComun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargando..." }));
        cboNombreComun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNombreComunActionPerformed(evt);
            }
        });

        txtNombreCientifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCientificoActionPerformed(evt);
            }
        });

        jLabel16.setText("Cantidad de Etiquetas");

        jLabel14.setText("Peso Neto");

        txtLote.setText("1");
        txtLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoteActionPerformed(evt);
            }
        });

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Esp.Veg.Tr", "Comun", "Fiscalizada", "Certificada", "Registrada", "Fundacion" }));
        cboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoriaActionPerformed(evt);
            }
        });

        txtPureza.setText("50");
        txtPureza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPurezaActionPerformed(evt);
            }
        });

        txtZaranda.setText("-");
        txtZaranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZarandaActionPerformed(evt);
            }
        });

        jLabel9.setText("%");

        jLabel8.setText("mm");

        jLabel4.setText("Pureza");

        jLabel3.setText("Lote");

        btnPrint.setBackground(new java.awt.Color(204, 255, 204));
        btnPrint.setText("IMPRIMIR");
        btnPrint.setEnabled(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnCancel.setText("CANCELAR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel2.setText("Categoria");

        jLabel1.setText("Genero Especie");

        txtCantidad.setText("1");
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        jLabel10.setText("%");

        jLabel12.setText("Kg");

        txtGerminacion.setText("45");
        txtGerminacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGerminacionActionPerformed(evt);
            }
        });

        txtTratamiento.setText("Sin tratemiento");
        txtTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTratamientoActionPerformed(evt);
            }
        });

        txtCosecha.setText("2014/2015");
        txtCosecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCosechaActionPerformed(evt);
            }
        });

        jLabel15.setText("Tratamiento");

        txtPeso.setText("15");
        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbVC);
        rbVC.setSelected(true);
        rbVC.setText("Valor Cultural");
        rbVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVCActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Germinacion Minima");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtPureza, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel9))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtZaranda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8))
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel12))
                        .addComponent(txtVariedad)
                        .addComponent(cboNombreComun, 0, 166, Short.MAX_VALUE)
                        .addComponent(txtNombreCientifico)
                        .addComponent(txtTratamiento)
                        .addComponent(txtCosecha, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(txtLote))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtGerminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(rbVC)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboNombreComun, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreCientifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVariedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(txtZaranda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPureza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGerminacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(rbVC)
                        .addComponent(jRadioButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCosecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtVariedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVariedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVariedadActionPerformed

    private void cboNombreComunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNombreComunActionPerformed
        try {
            if (cboNombreComun.getSelectedIndex() > -1) {
                semillaActual = (LabSemillasEspecies) cboNombreComun.getSelectedItem();

                txtNombreCientifico.setText(semillaActual.getEspecie());
                txtVariedad.setText(semillaActual.getVariedad());

                btnPrint.setEnabled(true);
            }
        } catch (Exception e) {
            MessageBox(e.getStackTrace().toString());
        }
    }//GEN-LAST:event_cboNombreComunActionPerformed

    public void MessageBox(String s) {
        JOptionPane.showMessageDialog(new JFrame(), s, "Dialog",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void txtNombreCientificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCientificoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCientificoActionPerformed

    private void txtLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoteActionPerformed

    private void cboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCategoriaActionPerformed

    private void txtPurezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPurezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPurezaActionPerformed

    private void txtZarandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZarandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZarandaActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        Utils.rawPrint(getZpl());
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtGerminacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGerminacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGerminacionActionPerformed

    private void txtTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTratamientoActionPerformed

    private void txtCosechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCosechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCosechaActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void rbVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVCActionPerformed

    public String getZpl() {

        nombreComun = cboNombreComun.getSelectedItem().toString();
        nombreCientifico = txtNombreCientifico.getText();
        variedad = txtVariedad.getText();
        categoria = cboCategoria.getSelectedItem().toString();
        lote = txtLote.getText();
        zaranda = txtZaranda.getText();
        if (!zaranda.equals("-")) {
            zaranda += "mm";
        }
        pureza = txtPureza.getText();
        germinacion = txtGerminacion.getText();
        cosecha = txtCosecha.getText();
        peso = txtPeso.getText();
        tratamiento = txtTratamiento.getText();

        String base = "^XA"
                + "^PW799"
                + "^CI27"
                //+ "^FT105,958^XGE:LC100.GRF,1,1^FS"
                + "^FT55,1026^XGE:LC100.GRF,2,2^FS"
                + "^FT320,1090^A0B,60,59^FB400,1,0,C^FH\\^FDCHORTITZER^FS"
                + "^FT390,1090^A0B,70,69^FB400,1,0,C\\^FDSEMILLAS^FS"
                + "^FT215,495^AAB,18,10FB280,1,0,C^FH\\^FDPegar Etiqueta DISE^FS"
                + "^FT450,195^A0B,23,24^FH\\^FDCosecha^FS"
                + "^FT525,195^A0B,30,29^FH\\^FD" + cosecha + "^FS"
                + "^FT450,345^A0B,23,24^FH\\^FDLote^FS"
                + "^FT525,345^A0B,30,29^FH\\^FD" + lote + "^FS"
                + "^FT450,495^A0B,23,24^FH\\^FDCategoria^FS"
                + "^FT525,495^A0B,30,29^FH\\^FD" + categoria + "^FS"
                + "^FT450,945^A0B,23,24^FB530,1,0,L^FH\\^FDGenero y Especie^FS"
                + "^FT525,945^A0B,50,49^FB530,1,0,L^FH\\^FD" + nombreCientifico + "^FS"
                + "^FT516,1090^A0B,28,28^FH\\^FDDATOS ^FS"
                + "^FT548,1090^A0B,28,28^FH\\^FDde la^FS"
                + "^FT582,1090^A0B,28,28^FH\\^FDSEMILLA^FS"
                + "^FT565,195^A0B,23,24^FH\\^FDZaranda^FS"
                + "^FT640,195^A0B,30,29^FH\\^FD" + zaranda + "^FS";
        if (rbVC.isSelected()) {
            base += "^FT565,345^A0B,23,24^FH\\^FDValor^FS"
                    + "^FT590,345^A0B,23,24^FH\\^FDCultural^FS";
        } else {
            base += "^FT565,345^A0B,23,24^FH\\^FDGerminacion^FS"
                    + "^FT590,345^A0B,23,24^FH\\^FDMinima^FS";
        }
        base += "^FT640,345^A0B,30,29^FH\\^FD" + germinacion + "%^FS"
                + "^FT565,495^A0B,23,24^FH\\^FDPureza^FS"
                + "^FT590,495^A0B,23,24^FH\\^FDMinima^FS"
                + "^FT640,495^A0B,30,29^FH\\^FD" + pureza + "%^FS"
                + "^FT565,945^A0B,23,24^FB530,1,0,L^FH\\^FDVariedad^FS"
                + "^FT640,945^A0B,50,49^FB530,1,0,L^FH\\^FD" + variedad + "^FS"
                + "^FT689,195^A0B,23,24^FH\\^FDRNPS Nº 346^FS"
                + "^FT719,195^A0B,23,24^FH\\^FDRNCS Nº 102^FS"
                + "^FT749,195^A0B,23,24^FH\\^FDRNLS Nº  07^FS"
                + "^FT680,495^A0B,23,24^FH\\^FDInsecticidas y Fungicidas^FS"
                + "^FT755,495^A0B,30,29^FH\\^FD" + tratamiento + "^FS"
                + "^FT750,1090^A0B,60,59^FH\\^FDPeso Neto: " + peso + " Kg^FS"
                + //lineas horiz
                "^FO55,55^GB0,645,2^FS"
                + "^FO420,55^GB0,1045,2^FS"
                + "^FO535,55^GB0,900,2^FS"
                + "^FO650,55^GB0,1045,2^FS"
                + "^FO765,55^GB0,1045,2^FS"
                + //lineas vert
                "^FO55,55^GB710,0,2^FS"
                + "^FO420,205^GB345,0,2^FS"
                + "^FO420,355^GB230,0,2^FS"
                + "^FO420,505^GB345,0,2^FS"
                + "^FO55,695^GB365,0,2^FS"
                + "^FO420,955^GB230,0,2^FS"
                + "^FO420,1100^GB475,0,2^FS"
                + "^PQ" + txtCantidad.getText() + ",1,0,Y^XZ";;

        return base;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboCategoria;
    private javax.swing.JComboBox cboNombreComun;
    private javax.persistence.EntityManager em;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton rbVC;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCosecha;
    private javax.swing.JTextField txtGerminacion;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtNombreCientifico;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPureza;
    private javax.swing.JTextField txtTratamiento;
    private javax.swing.JTextField txtVariedad;
    private javax.swing.JTextField txtZaranda;
    // End of variables declaration//GEN-END:variables
}
